[package]
name = "weakauras-codec-lua-value"
version = "0.1.1"
authors = ["Velithris"]
license = "MIT"
description = "Provides types that behave similarly to Lua types."
keywords.workspace = true
repository.workspace = true
documentation = "https://docs.rs/weakauras-codec-lua-value"
edition = "2024"
rust-version = "1.87"

[features]
default = []
arbitrary = ["dep:arbitrary", "indexmap?/arbitrary"]
fnv = ["dep:fnv"]
indexmap = ["dep:indexmap"]
serde = ["dep:serde_core", "dep:serde"]

[dependencies]
arbitrary = { version = "1.4.2", features = ["derive"], optional = true }
fnv = { version = "1.0.7", optional = true }
indexmap = { version = "2.11.4", optional = true }
serde_core = { version = "1.0.226", optional = true }

# If someone depends on this crate and on serde at the same time,
# make sure that the latter is at least 1.0.220.
[target.'cfg(any())'.dependencies]
serde = { version = "1.0.220", default-features = false, optional = true }

[package.metadata.docs.rs]
features = ["arbitrary", "serde"]
